FROM php:7.2-fpm

# Instalando dependências
RUN apt-get update && apt-get install -y \
    nginx \
    && docker-php-ext-install mysqli pdo_mysql \
    && chown -R www-data:www-data /var/www/html

CMD ["php-fpm"]